apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aesk-1-51-go
  janus-idp.io/tekton: aesk-1-51-go
  backstage.io/kubernetes-id: aesk-1-51-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aesk-1-51-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
